Update reusable-workflow-template.yml

diff --git a/.github/workflows/reusable-workflow-template.yml b/.github/workflows/reusable-workflow-template.yml
--- a/.github/workflows/reusable-workflow-template.yml
+++ b/.github/workflows/reusable-workflow-template.yml
@@ -3,6 +3,7 @@ name: 04-1. Call Reusable Workflow Templates
 on: 
   [workflow_dispatch]
 
+
 jobs:
   call_greet_everyone_workflow_job:
     uses: githubabcs/gh-abcs-actions/.github/workflows/greet-everyone.yml@main
@@ -11,7 +12,17 @@ jobs:
     
   call_reusable_workflow_job:
     uses: githubabcs/gh-abcs-actions/.github/workflows/super-linter.yml@main
-
+  
+  
+    
+  job:
+    runs-on: windows-latest
+    steps:
+      - name: A/B Check
+        if: ${{ envA }} != ${{ envB }}
+        run: |
+          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+          exit 1
   call_demo_workflow_job:
     needs: call_greet_everyone_workflow_job
     uses: githubabcs/gh-abcs-actions/.github/workflows/github-actions-demo.yml@main
